services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        tty: true
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            MESA_LOADER_DRIVER_OVERRIDE: swrast
            EGL_PLATFORM: surfaceless
            # Dconf workarounds
            GSETTINGS_BACKEND: memory
            DCONF_PROFILE: /dev/null
            # Tauri settings
            TAURI_SKIP_DEVSERVER_CHECK: 1
            TAURI_CLI_SKIP_SLOW_DEVICES_CHECK: 1
            RUSTFLAGS: "--cfg=web_sys_unstable_apis"
        volumes:
            - '.:/var/www/html'
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            # Optional but recommended for WSL X server
            - "${HOME}/.Xauthority:/home/sail/.Xauthority:ro"
        networks:
            - sail
        depends_on:
            - mysql
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost"]
            retries: 3
            timeout: 5s
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - '8090:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 300M
        networks:
        - sail
        restart: always
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
