name: Docker Setup Validation

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ main, dev ]

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to Docker Hub (if needed)
      #   if: startsWith(github.repository, 'your-org/your-repository')
      #   uses: docker/login-action@v4
      #   with:
      #     registry: 'docker.io'
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Validate Docker Compose
        run: |
          # Check if docker-compose is installed
          command -v docker-compose &> /dev/null || { echo "Docker Compose is not installed"; exit 1; }

          # Validate the syntax of docker-compose.yml
          docker-compose config --validate > /dev/null || { echo "Docker Compose file is invalid"; exit 1; }

          # Check if all dependencies are valid
          docker-compose dependency list --check > /dev/null || { echo "Docker Compose dependencies are invalid"; exit 1; }

      - name: Save Docker configuration for review (optional)
        uses: actions/upload-artifact@v4
        with:
          name: docker-configuration
          path: ./docker/*
